backend:
  name: git-gateway

media_folder: source/images/
public_folder: /images/

site_url: https://www.mountadamschallenge.org/
display_url: https://www.mountadamschallenge.org/
show_preview_links: false

collections:
  #yaml middleman data example
  - name: results
    label: Results
    label_singular: Result
    identifier_field: name
    format: yml
    extension: yml
    folder: data/results
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{last_name}}'
    fields:
      - {label: Last Name, name: last_name, widget: string, required: true}
      - {label: First Name, name: first_name, widget: string, required: true}
      - {label: Run Date, name: run_date, widget: datetime, required: true}
      - {label: Run Time, name: run_time, widget: string, default: "2:09:59", required: true}
    summary: "{{run_date}} - {{last_name}}"
